// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the Scenes Server plugin.

// Token header for the Level Control Server plugin.

// Token header for the On/Off Server plugin.

// Token header for the ZCL Core plugin.

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

