// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void ezModeEventHandler(void);
extern EmberEventControl ezModeEventControl;

void stateEventHandler(void);
extern EmberEventControl stateEventControl;

void emZclOtaBootloadStorageEepromEraseEventHandler(void);
extern EmberEventControl emZclOtaBootloadStorageEepromEraseEventControl;

void emZclEzModeEventHandler(void);
extern EmberEventControl emZclEzModeEventControl;

void emZclIdentifyServerEventHandler(void);
extern EmberEventControl emZclIdentifyServerEventControl;

void emZclOtaBootloadClientEventHandler(void);
extern EmberEventControl emZclOtaBootloadClientEventControl;



const EmberEventData emAppEvents[] = {
  {&ezModeEventControl, ezModeEventHandler},
  {&stateEventControl, stateEventHandler},
  {&emZclOtaBootloadStorageEepromEraseEventControl, emZclOtaBootloadStorageEepromEraseEventHandler},
  {&emZclEzModeEventControl, emZclEzModeEventHandler},
  {&emZclIdentifyServerEventControl, emZclIdentifyServerEventHandler},
  {&emZclOtaBootloadClientEventControl, emZclOtaBootloadClientEventHandler},
  {NULL, NULL}
};
