// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_THREAD_BOOKKEEPING_H
#define SILABS_THREAD_BOOKKEEPING_H


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_ZCL_CORE
#include EMBER_AF_API_ZCL_SCENES_SERVER
#include EMBER_AF_API_STACK

void emZclEraseScene(uint8_t tableIdx);

bool emZclAddScene(EmberZclClusterId_t clusterId, uint8_t tableIdx, const uint8_t *sceneData, uint8_t length);

void emZclRecallScene(EmberZclEndpointId_t endpointId, uint8_t tableIdx, uint32_t transitionTime100mS);

void emZclStoreScene(EmberZclEndpointId_t endpointId, uint8_t tableIdx);

void emZclCopyScene(uint8_t srcTableIdx, uint8_t dstTableIdx);

void emZclViewScene(uint8_t tableIdx, uint8_t **ppExtFldData);

void emZclPrintInfoScene(uint8_t tableIdx);

bool emZclPreAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclPostAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclNotification(const EmberZclNotificationContext_t *context, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

bool emberAfOkToSleep(uint32_t durationMs);

void emberAfPluginIdleSleepWakeUp(uint32_t durationMs);

bool emberAfOkToIdle(uint32_t durationMs);

void emberAfPluginIdleSleepActive(uint32_t durationMs);

void emAfMain(MAIN_FUNCTION_PARAMETERS);

void emAfInit(void);

void emAfTick(void);

void emAfMarkApplicationBuffers(void);

void emberNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);

#endif // SILABS_THREAD_BOOKKEEPING_H
