// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_THREAD_CONFIG
#define SILABS_THREAD_CONFIG




// Top level macros
#define EMBER_AF_DEVICE_NAME "light"


// Generated setup headers that are included automatically
#include "thread-debug-print.h"


// Generated plugin macros

// Use this macro to check if ADC plugin is included
#define EMBER_AF_PLUGIN_ADC

// Use this macro to check if Address Configuration Debug plugin is included
#define EMBER_AF_PLUGIN_ADDRESS_CONFIGURATION_DEBUG

// Use this macro to check if Antenna Stub plugin is included
#define EMBER_AF_PLUGIN_ANTENNA_STUB

// Use this macro to check if Basic Server plugin is included
#define EMBER_AF_PLUGIN_BASIC_SERVER

// Use this macro to check if Button plugin is included
#define EMBER_AF_PLUGIN_BUTTON

// Use this macro to check if Buzzer plugin is included
#define EMBER_AF_PLUGIN_BUZZER

// Use this macro to check if CLI plugin is included
#define EMBER_AF_PLUGIN_CLI

// Use this macro to check if CoAP Dispatch plugin is included
#define EMBER_AF_PLUGIN_COAP_DISPATCH

// Use this macro to check if Radio Coexistence Stub plugin is included
#define EMBER_AF_PLUGIN_COEXISTENCE_STUB

// Use this macro to check if Command Interpreter plugin is included
#define EMBER_AF_PLUGIN_COMMAND_INTERPRETER2

// Use this macro to check if Debug JTAG plugin is included
#define EMBER_AF_PLUGIN_DEBUG_CHANNEL

// Use this macro to check if Debug Print plugin is included
#define EMBER_AF_PLUGIN_DEBUG_PRINT
// User options for plugin Debug Print
#define EMBER_AF_DEBUG_PRINT_USE_PORT

// Use this macro to check if Dynamic Host Configuration Protocol (DHCP) Client plugin is included
#define EMBER_AF_PLUGIN_DHCP_CLIENT

// Use this macro to check if DHCP Library plugin is included
#define EMBER_AF_PLUGIN_DHCP_LIBRARY

// Use this macro to check if Diagnostic Stub plugin is included
#define EMBER_AF_PLUGIN_DIAGNOSTIC_STUB

// Use this macro to check if DTLS Authentication Parameters plugin is included
#define EMBER_AF_PLUGIN_DTLS_AUTH_PARAMS
// User options for plugin DTLS Authentication Parameters

// Use this macro to check if EEPROM plugin is included
#define EMBER_AF_PLUGIN_EEPROM
// User options for plugin EEPROM
#define EMBER_AF_PLUGIN_EEPROM_PARTIAL_WORD_STORAGE_COUNT 2

// Use this macro to check if Groups Server plugin is included
#define EMBER_AF_PLUGIN_GROUPS_SERVER
// User options for plugin Groups Server
#define EMBER_AF_PLUGIN_GROUPS_SERVER_MAX_GROUP_NAME_LENGTH 0

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_HAL_LIBRARY

// Use this macro to check if Heartbeat plugin is included
#define EMBER_AF_PLUGIN_HEARTBEAT
// User options for plugin Heartbeat
#define EMBER_AF_PLUGIN_HEARTBEAT_PERIOD_QS 1

// Use this macro to check if ICMP Debug plugin is included
#define EMBER_AF_PLUGIN_ICMP_DEBUG

// Use this macro to check if Identify Server plugin is included
#define EMBER_AF_PLUGIN_IDENTIFY_SERVER

// Use this macro to check if Idle/Sleep plugin is included
#define EMBER_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define EMBER_AF_PLUGIN_IDLE_SLEEP_MINIMUM_SLEEP_DURATION_MS 5

// Use this macro to check if LED plugin is included
#define EMBER_AF_PLUGIN_LED

// Use this macro to check if Level Control Server plugin is included
#define EMBER_AF_PLUGIN_LEVEL_CONTROL_SERVER
// User options for plugin Level Control Server
#define EMBER_AF_PLUGIN_LEVEL_CONTROL_SERVER_MAXIMUM_LEVEL 255
#define EMBER_AF_PLUGIN_LEVEL_CONTROL_SERVER_MINIMUM_LEVEL 0

// Use this macro to check if Main plugin is included
#define EMBER_AF_PLUGIN_MAIN

// Use this macro to check if mbed TLS Library plugin is included
#define EMBER_AF_PLUGIN_MBEDTLS_DOTDOT_LIBRARY

// Use this macro to check if Manufacturing Library plugin is included
#define EMBER_AF_PLUGIN_MFGLIB_LIBRARY

// Use this macro to check if NVM3 Library plugin is included
#define EMBER_AF_PLUGIN_NVM3
// User options for plugin NVM3 Library
#define EMBER_AF_PLUGIN_NVM3_FLASH_PAGES 18
#define EMBER_AF_PLUGIN_NVM3_CACHE_SIZE 200
#define EMBER_AF_PLUGIN_NVM3_MAX_OBJECT_SIZE 254
#define EMBER_AF_PLUGIN_NVM3_USER_REPACK_HEADROOM 0

// Use this macro to check if On/Off Server plugin is included
#define EMBER_AF_PLUGIN_ON_OFF_SERVER

// Use this macro to check if OTA Bootload Client plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT
// User options for plugin OTA Bootload Client
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_AUTO_START
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_BLOCK_ERROR_THRESHOLD 5
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_DISCOVER_SERVER_PERIOD_MINUTES 10
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_QUERY_NEXT_IMAGE_PERIOD_MINUTES 60

// Use this macro to check if OTA Bootload Client Policy plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY
// User options for plugin OTA Bootload Client Policy
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_LOOKUP_TYPE EMBER_ZCL_OTA_DISCOVER
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_SCHEME_PARAMETER EMBER_ZCL_SCHEME_COAP
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_NAME {0x06, 's', 'i', 'l', 'a', 'b', 's', 0x03, 'c', 'o', 'm', 0x00}
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_NAME_LENGTH (12)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ADDRESS_PARAMETER {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ADDRESS_PARAMETER_LENGTH (16)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_PORT_PARAMETER 65535
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_UID_PARAMETER { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_UID_PARAMETER_LENGTH (32)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ENDPOINT_PARAMETER 1
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_MANUFACTURER_CODE 4660
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_TYPE 22136
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_VERSION 16843009
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_HARDWARE_VERSION 1
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_DELETE_EXISTING_IMAGES_BEFORE_DOWNLOAD

// Use this macro to check if OTA Bootload Core plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CORE

// Use this macro to check if OTA Bootload Storage Core plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_CORE

// Use this macro to check if OTA Bootload Storage EEPROM plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM
// User options for plugin OTA Bootload Storage EEPROM
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM_START_ADDRESS 0
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM_END_ADDRESS 204799

// Use this macro to check if RAIL Library Multiprotocol plugin is included
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_MP
// User options for plugin RAIL Library Multiprotocol
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_MP_RAILPHYDEF 1
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_MP_RAILMPPHYDEF 1

// Use this macro to check if Scan Debug plugin is included
#define EMBER_AF_PLUGIN_SCAN_DEBUG

// Use this macro to check if Scenes Server plugin is included
#define EMBER_AF_PLUGIN_SCENES_SERVER
// User options for plugin Scenes Server
#define EMBER_AF_PLUGIN_SCENES_SERVER_TABLE_SIZE 1

// Use this macro to check if Serial plugin is included
#define EMBER_AF_PLUGIN_SERIAL

// Use this macro to check if Simulated EEPROM version 2 to NVM3 Upgrade Stub plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM2_TO_NVM3_UPGRADE_STUB

// Use this macro to check if Stateless Address Autoconfiguration (SLAAC) Client plugin is included
#define EMBER_AF_PLUGIN_SLAAC_CLIENT

// Use this macro to check if Thread Stack Library with mbed TLS support plugin is included
#define EMBER_AF_PLUGIN_THREAD_MBEDTLS_STACK

// Use this macro to check if UDP Debug plugin is included
#define EMBER_AF_PLUGIN_UDP_DEBUG

// Use this macro to check if Version Debug plugin is included
#define EMBER_AF_PLUGIN_VERSION_DEBUG

// Use this macro to check if ZCL Core plugin is included
#define EMBER_AF_PLUGIN_ZCL_CORE
// User options for plugin ZCL Core
#define EMBER_ZCL_BINDING_TABLE_SIZE 8
#define EMBER_ZCL_CACHE_TABLE_SIZE 8
#define EMBER_ZCL_GROUP_TABLE_SIZE 4
#define EMBER_ZCL_REPORTING_CONFIGURATIONS_TABLE_SIZE 4

// Use this macro to check if ZCL Core CLI plugin is included
#define EMBER_AF_PLUGIN_ZCL_CORE_CLI


// Generated API headers

// API adc-cortexm3 from ADC plugin
#define EMBER_AF_API_ADC_CORTEXM3 "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/adc/adc-cortexm3.h"

// API adc from ADC plugin
#define EMBER_AF_API_ADC "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/adc/adc.h"

// API antenna from Antenna Stub plugin
#define EMBER_AF_API_ANTENNA "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/antenna/antenna.h"

// API button from Button plugin
#define EMBER_AF_API_BUTTON "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/button.h"

// API buzzer from Buzzer plugin
#define EMBER_AF_API_BUZZER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/buzzer/buzzer.h"

// API coap-dispatch from CoAP Dispatch plugin
#define EMBER_AF_API_COAP_DISPATCH "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/coap-dispatch/coap-dispatch.h"

// API coexistence from Radio Coexistence Stub plugin
#define EMBER_AF_API_COEXISTENCE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154/coexistence-802154.h"

// API command-interpreter2 from Command Interpreter plugin
#define EMBER_AF_API_COMMAND_INTERPRETER2 "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/util/serial/command-interpreter2.h"

// API debug-print from Debug Print plugin
#define EMBER_AF_API_DEBUG_PRINT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/debug-print/debug-print.h"

// API diagnostic from Diagnostic Stub plugin
#define EMBER_AF_API_DIAGNOSTIC "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/diagnostic.h"

// API eeprom from EEPROM plugin
#define EMBER_AF_API_EEPROM "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/util/plugin/plugin-common/eeprom/eeprom.h"

// API eeprom-print from EEPROM plugin
#define EMBER_AF_API_EEPROM_PRINT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/util/plugin/plugin-afv6/eeprom/eeprom-print.h"

// API crc from HAL Library plugin
#define EMBER_AF_API_CRC "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/crc.h"

// API endian from HAL Library plugin
#define EMBER_AF_API_ENDIAN "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/endian.h"

// API hal from HAL Library plugin
#define EMBER_AF_API_HAL "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/hal.h"

// API random from HAL Library plugin
#define EMBER_AF_API_RANDOM "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/random.h"

// API system-timer from HAL Library plugin
#define EMBER_AF_API_SYSTEM_TIMER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/system-timer.h"

// API token-cortexm3 from HAL Library plugin
#define EMBER_AF_API_TOKEN_CORTEXM3 "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/cortexm3/token.h"

// API token from HAL Library plugin
#define EMBER_AF_API_TOKEN "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/token.h"

// API led from LED plugin
#define EMBER_AF_API_LED "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/led.h"

// API zcl-level-control-server from Level Control Server plugin
#define EMBER_AF_API_ZCL_LEVEL_CONTROL_SERVER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/level-control-server/level-control-server.h"

// API mfglib from Manufacturing Library plugin
#define EMBER_AF_API_MFGLIB "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/mfglib.h"

// API nvm3 from NVM3 Library plugin
#define EMBER_AF_API_NVM3 "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/nvm3/nvm3-token.h"

// API zcl-ota-bootload-client from OTA Bootload Client plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_CLIENT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/ota-bootload-client/ota-bootload-client.h"

// API zcl-ota-bootload-core from OTA Bootload Core plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_CORE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/ota-bootload-core/ota-bootload-core.h"

// API zcl-ota-bootload-storage-core from OTA Bootload Storage Core plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_STORAGE_CORE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/ota-bootload-storage-core/ota-bootload-storage-core.h"

// API rail-library from RAIL Library Multiprotocol plugin
#define EMBER_AF_API_RAIL_LIBRARY "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/common/rail.h"

// API zcl-scenes-server from Scenes Server plugin
#define EMBER_AF_API_ZCL_SCENES_SERVER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/scenes-server/scenes-server.h"

// API serial from Serial plugin
#define EMBER_AF_API_SERIAL "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/serial/serial.h"

// API buffer-management from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_BUFFER_MANAGEMENT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/buffer-management.h"

// API buffer-queue from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_BUFFER_QUEUE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/buffer-queue.h"

// API child from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_CHILD "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/child.h"

// API coap-diagnostic from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_COAP_DIAGNOSTIC "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-diagnostics.h"

// API coap from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_COAP "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/coap.h"

// API event-queue from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_EVENT_QUEUE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/event-queue.h"

// API event from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_EVENT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/event.h"

// API icmp from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_ICMP "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/icmp.h"

// API network-diagnostics from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_NETWORK_DIAGNOSTICS "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-diagnostics.h"

// API network-management from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_NETWORK_MANAGEMENT "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-management.h"

// API stack-info from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_STACK_INFO "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/stack-info.h"

// API stack from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_STACK "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/ember.h"

// API tcp from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_TCP "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/tcp.h"

// API udp-peer from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_UDP_PEER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/udp-peer.h"

// API udp from Thread Stack Library with mbed TLS support plugin
#define EMBER_AF_API_UDP "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/udp.h"

// API zcl-core from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/zcl-core/zcl-core.h"

// API zcl-core-well-known from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE_WELL_KNOWN "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/zcl-core/zcl-core-well-known.h"

// API zcl-core-dtls-manager from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE_DTLS_MANAGER "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/zcl-core/zcl-core-dtls-manager.h"

// API zcl-core-resource-directory from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE_RESOURCE_DIRECTORY "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/zcl-core/zcl-core-resource-directory.h"


// Coap Dispatch macros
#ifdef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#undef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#endif
#define EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH 17


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG12P332F1024GL125

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 2

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 332

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 1024K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE L

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 125

#ifdef EMBER_AF_RADIO_MODULE
#undef EMBER_AF_RADIO_MODULE
#endif
#define EMBER_AF_RADIO_MODULE XX

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG12P332F1024GL125

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 2

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 332

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 1024K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE L

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 125

#ifdef EMBER_AF_MCU_MODULE
#undef EMBER_AF_MCU_MODULE
#endif
#define EMBER_AF_MCU_MODULE XX

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4162A

#ifdef EMBER_ZCL_MAX_GROUP_NAME_LENGTH
#undef EMBER_ZCL_MAX_GROUP_NAME_LENGTH
#endif
#define EMBER_ZCL_MAX_GROUP_NAME_LENGTH 0



#endif // SILABS_THREAD_CONFIG
