// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_EMBER_TYPES
#ifdef EMBER_AF_API_THREAD_TEST_HARNESS_CLI
#include EMBER_AF_API_THREAD_TEST_HARNESS_CLI
#endif
#include EMBER_AF_API_COMMAND_INTERPRETER2

void emAfEepromDataPrintCommand(void);
void emAfEepromInfoCommand(void);
void emAfEepromStatusCommand(void);
static EmberCommandEntry emberCommandEepromTable[] = {
  emberCommandEntryAction("data-print", emAfEepromDataPrintCommand, "w", ""),
  emberCommandEntryAction("info", emAfEepromInfoCommand, "", ""),
  emberCommandEntryAction("status", emAfEepromStatusCommand, "", ""),
  emberCommandEntryTerminator(),
};
void emberPrintCommandTable(void);
void otaBootloadClientForceUpdate(void);
static EmberCommandEntry emberCommandOtaBootloadClientTable[] = {
  emberCommandEntryAction("update", otaBootloadClientForceUpdate, "", ""),
  emberCommandEntryTerminator(),
};
void emberResetMicro(void);
void emZclCliAccessControlModeCommand(void);
void emZclCliAccessControlPrintCommand(void);
static EmberCommandEntry emberCommandZclAccessControlTable[] = {
  emberCommandEntryAction("mode", emZclCliAccessControlModeCommand, "u", ""),
  emberCommandEntryAction("print", emZclCliAccessControlPrintCommand, "", ""),
  emberCommandEntryTerminator(),
};
void emZclCliAttributePrintCommand(void);
void emZclCliAttributeReadCommand(void);
void emZclCliAttributeRemoteReadCommand(void);
void emZclCliAttributeRemoteWriteCommand(void);
static EmberCommandEntry emberCommandZclAttributeRemoteTable[] = {
  emberCommandEntryAction("read", emZclCliAttributeRemoteReadCommand, "uvvv*", ""),
  emberCommandEntryAction("write", emZclCliAttributeRemoteWriteCommand, "uvvvb", ""),
  emberCommandEntryTerminator(),
};
void emZclCliAttributeResetCommand(void);
void emZclCliAttributeWriteCommand(void);
static EmberCommandEntry emberCommandZclAttributeTable[] = {
  emberCommandEntryAction("print", emZclCliAttributePrintCommand, "", ""),
  emberCommandEntryAction("read", emZclCliAttributeReadCommand, "uuvvv", ""),
  emberCommandEntrySubMenu("remote", emberCommandZclAttributeRemoteTable, ""),
  emberCommandEntryAction("reset", emZclCliAttributeResetCommand, "u", ""),
  emberCommandEntryAction("write", emZclCliAttributeWriteCommand, "uuvvvb", ""),
  emberCommandEntryTerminator(),
};
void emZclCliBindingAddSetCommand(void);
void emZclCliBindingClearCommand(void);
void emZclCliBindingPrintCommand(void);
void emZclCliBindingRemoteAddUpdateCommand(void);
void emZclCliBindingRemoteRemoveCommand(void);
void emZclCliBindingRemoteAddUpdateCommand(void);
static EmberCommandEntry emberCommandZclBindingRemoteTable[] = {
  emberCommandEntryAction("add", emZclCliBindingRemoteAddUpdateCommand, "uvvubvuvu", ""),
  emberCommandEntryAction("remove", emZclCliBindingRemoteRemoveCommand, "uvvu", ""),
  emberCommandEntryAction("update", emZclCliBindingRemoteAddUpdateCommand, "uvvubvuvuu", ""),
  emberCommandEntryTerminator(),
};
void emZclCliBindingRemoveCommand(void);
void emZclCliBindingAddSetCommand(void);
static EmberCommandEntry emberCommandZclBindingTable[] = {
  emberCommandEntryAction("add", emZclCliBindingAddSetCommand, "uuvvubvuvu", ""),
  emberCommandEntryAction("clear", emZclCliBindingClearCommand, "", ""),
  emberCommandEntryAction("print", emZclCliBindingPrintCommand, "", ""),
  emberCommandEntrySubMenu("remote", emberCommandZclBindingRemoteTable, ""),
  emberCommandEntryAction("remove", emZclCliBindingRemoveCommand, "u", ""),
  emberCommandEntryAction("set", emZclCliBindingAddSetCommand, "uuvvubvuvuu", ""),
  emberCommandEntryTerminator(),
};
void emZclCliCacheAddCommand(void);
static EmberCommandEntry emberCommandZclCacheAddTable[] = {
  emberCommandEntryAction("uid-ipv6", emZclCliCacheAddCommand, "bb", ""),
  emberCommandEntryTerminator(),
};
void emZclCliCacheClearCommand(void);
void emZclCliCachePrintCommand(void);
void emZclCliCacheRemoveCommand(void);
static EmberCommandEntry emberCommandZclCacheTable[] = {
  emberCommandEntrySubMenu("add", emberCommandZclCacheAddTable, ""),
  emberCommandEntryAction("clear", emZclCliCacheClearCommand, "", ""),
  emberCommandEntryAction("print", emZclCliCachePrintCommand, "uu", ""),
  emberCommandEntryAction("remove", emZclCliCacheRemoveCommand, "v", ""),
  emberCommandEntryTerminator(),
};
void emZclCliCborForceDefiniteLenCommand(void);
static EmberCommandEntry emberCommandZclCborTable[] = {
  emberCommandEntryAction("force-definite-len", emZclCliCborForceDefiniteLenCommand, "u", ""),
  emberCommandEntryTerminator(),
};
void emZclCliDiscSetAcceptCommand(void);
void emZclCliDiscByClusterIdCommand(void);
void emZclCliDiscByClusterRevisionCommand(void);
void emZclCliDiscByDeviceTypeCommand(void);
void emZclCliDiscByEndpointCommand(void);
void emZclCliDiscInitCommand(void);
void emZclCliDiscSetModeCommand(void);
void emZclCliDiscByResourceVersionCommand(void);
void emZclCliDiscSendCommand(void);
void emZclCliDiscByUidCommand(void);
static EmberCommandEntry emberCommandZclDiscoveryTable[] = {
  emberCommandEntryAction("accept", emZclCliDiscSetAcceptCommand, "v", ""),
  emberCommandEntryAction("cluster", emZclCliDiscByClusterIdCommand, "uvv", ""),
  emberCommandEntryAction("cluster-revision", emZclCliDiscByClusterRevisionCommand, "v", ""),
  emberCommandEntryAction("device-type", emZclCliDiscByDeviceTypeCommand, "v", ""),
  emberCommandEntryAction("endpoint", emZclCliDiscByEndpointCommand, "uv", ""),
  emberCommandEntryAction("init", emZclCliDiscInitCommand, "", ""),
  emberCommandEntryAction("mode", emZclCliDiscSetModeCommand, "u", ""),
  emberCommandEntryAction("resource-version", emZclCliDiscByResourceVersionCommand, "v", ""),
  emberCommandEntryAction("send", emZclCliDiscSendCommand, "", ""),
  emberCommandEntryAction("uid", emZclCliDiscByUidCommand, "b", ""),
  emberCommandEntryTerminator(),
};
void emZclCliEzModeStartCommand(void);
void emberZclStopEzMode(void);
static EmberCommandEntry emberCommandZclEzModeTable[] = {
  emberCommandEntryAction("start", emZclCliEzModeStartCommand, "", ""),
  emberCommandEntryAction("stop", emberZclStopEzMode, "", ""),
  emberCommandEntryTerminator(),
};
void emZclCliInfoCommand(void);
void emZclResourceDirectoryRegisterCommand(void);
static EmberCommandEntry emberCommandZclResourceDirectoryTable[] = {
  emberCommandEntryAction("register", emZclResourceDirectoryRegisterCommand, "bv", ""),
  emberCommandEntryTerminator(),
};
void emZclCliSendCommand(void);
void emZclCliSendCommand(void);
void emZclCliSendCommand(void);
static EmberCommandEntry emberCommandZclSendTable[] = {
  emberCommandEntryAction("binding", emZclCliSendCommand, "u", ""),
  emberCommandEntryAction("endpoint", emZclCliSendCommand, "ubu", ""),
  emberCommandEntryAction("group", emZclCliSendCommand, "bv", ""),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandZclTable[] = {
  emberCommandEntrySubMenu("access-control", emberCommandZclAccessControlTable, ""),
  emberCommandEntrySubMenu("attribute", emberCommandZclAttributeTable, ""),
  emberCommandEntrySubMenu("binding", emberCommandZclBindingTable, ""),
  emberCommandEntrySubMenu("cache", emberCommandZclCacheTable, ""),
  emberCommandEntrySubMenu("cbor", emberCommandZclCborTable, ""),
  emberCommandEntrySubMenu("discovery", emberCommandZclDiscoveryTable, ""),
  emberCommandEntrySubMenu("ez-mode", emberCommandZclEzModeTable, ""),
  emberCommandEntryAction("info", emZclCliInfoCommand, "", ""),
  emberCommandEntrySubMenu("resource-directory", emberCommandZclResourceDirectoryTable, ""),
  emberCommandEntrySubMenu("send", emberCommandZclSendTable, ""),
  emberCommandEntryTerminator(),
};
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntrySubMenu("eeprom", emberCommandEepromTable, ""),
  emberCommandEntryAction("help", emberPrintCommandTable, "", ""),
  emberCommandEntrySubMenu("ota-bootload-client", emberCommandOtaBootloadClientTable, ""),
  emberCommandEntryAction("reset", emberResetMicro, "", ""),
  emberCommandEntrySubMenu("zcl", emberCommandZclTable, ""),
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
