// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the static data to populate all ZCL structs for the configured device.
#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_ZCL_CORE
#include "thread-callbacks.h"

// -----------------------------------------------------------------------------
// Basic cluster (0x0000).

// Basic cluster client (0x0000).
const EmberZclClusterSpec_t emberZclClusterBasicClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_BASIC,
};

// Basic cluster server (0x0000).
const EmberZclClusterSpec_t emberZclClusterBasicServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_BASIC,
};

// Basic cluster server (0x0000) - ResetToFactoryDefaults (0x00) command.
#define emZclClusterBasicServerCommandResetToFactoryDefaultsRequestSpec NULL
static const ZclipStructSpec emZclClusterBasicServerCommandResetToFactoryDefaultsResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterBasicServerCommandResetToFactoryDefaultsResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterBasicServerCommandResetToFactoryDefaultsResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterBasicServerCommandResetToFactoryDefaultsResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterBasicServerCommandResetToFactoryDefaultsResponseSpec);
}

// -----------------------------------------------------------------------------
// Identify cluster (0x0003).

// Identify cluster client (0x0003).
const EmberZclClusterSpec_t emberZclClusterIdentifyClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_IDENTIFY,
};

// Identify cluster server (0x0003).
const EmberZclClusterSpec_t emberZclClusterIdentifyServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_IDENTIFY,
};

// Identify cluster server (0x0003) - Identify (0x00) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, identifyTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandIdentifyResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandIdentifyResponseSpec);
}

// Identify cluster server (0x0003) - IdentifyQuery (0x01) command.
#define emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec NULL
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyQueryResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyQueryResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, timeout),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyQueryResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandIdentifyQueryResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandIdentifyQueryResponseSpec);
}

// Identify cluster server (0x0003) - EZModeInvoke (0x02) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandEZModeInvokeRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, action),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandEZModeInvokeResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandEZModeInvokeResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandEZModeInvokeResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandEZModeInvokeResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandEZModeInvokeResponseSpec);
}

// Identify cluster server (0x0003) - UpdateCommissionState (0x03) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandUpdateCommissionStateRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandUpdateCommissionStateRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, action),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, commissionStateMask),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandUpdateCommissionStateResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandUpdateCommissionStateResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandUpdateCommissionStateResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandUpdateCommissionStateResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandUpdateCommissionStateResponseSpec);
}

// Identify cluster server (0x0003) - TriggerEffect (0x40) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandTriggerEffectRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandTriggerEffectRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectVariant),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandTriggerEffectResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandTriggerEffectResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandTriggerEffectResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandTriggerEffectResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandTriggerEffectResponseSpec);
}

// -----------------------------------------------------------------------------
// Groups cluster (0x0004).

// Groups cluster client (0x0004).
const EmberZclClusterSpec_t emberZclClusterGroupsClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_GROUPS,
};

// Groups cluster server (0x0004).
const EmberZclClusterSpec_t emberZclClusterGroupsServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_GROUPS,
};

// Groups cluster server (0x0004) - AddGroup (0x00) command.
static const ZclipStructSpec emZclClusterGroupsServerCommandAddGroupRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandAddGroupRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, groupName),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, addrAssignmentMode, 1),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_BINARY, groupMcastAddress, 2),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupUdpPort, 3),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterGroupsServerCommandAddGroupResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandAddGroupResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandAddGroupResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandAddGroupResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandAddGroupResponseSpec);
}

// Groups cluster server (0x0004) - ViewGroup (0x01) command.
static const ZclipStructSpec emZclClusterGroupsServerCommandViewGroupRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandViewGroupRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterGroupsServerCommandViewGroupResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandViewGroupResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 6, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, groupName),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, addrAssignmentMode, 1),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_BINARY, groupMcastAddress, 2),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupUdpPort, 3),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandViewGroupResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandViewGroupResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandViewGroupResponseSpec);
}

// Groups cluster server (0x0004) - GetGroupMembership (0x02) command.
static const ZclipStructSpec emZclClusterGroupsServerCommandGetGroupMembershipRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandGetGroupMembershipRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD_ARRAY(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupList),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterGroupsServerCommandGetGroupMembershipResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandGetGroupMembershipResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, capacity),
  EMBER_ZCLIP_FIELD_ARRAY(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupList),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandGetGroupMembershipResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandGetGroupMembershipResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandGetGroupMembershipResponseSpec);
}

// Groups cluster server (0x0004) - RemoveGroup (0x03) command.
static const ZclipStructSpec emZclClusterGroupsServerCommandRemoveGroupRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandRemoveGroupRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterGroupsServerCommandRemoveGroupResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandRemoveGroupResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandRemoveGroupResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandRemoveGroupResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandRemoveGroupResponseSpec);
}

// Groups cluster server (0x0004) - RemoveAllGroups (0x04) command.
#define emZclClusterGroupsServerCommandRemoveAllGroupsRequestSpec NULL
static const ZclipStructSpec emZclClusterGroupsServerCommandRemoveAllGroupsResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandRemoveAllGroupsResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandRemoveAllGroupsResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandRemoveAllGroupsResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandRemoveAllGroupsResponseSpec);
}

// Groups cluster server (0x0004) - AddGroupIfIdentifying (0x05) command.
static const ZclipStructSpec emZclClusterGroupsServerCommandAddGroupIfIdentifyingRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandAddGroupIfIdentifyingRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, groupName),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, addrAssignmentMode, 1),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_BINARY, groupMcastAddress, 2),
  EMBER_ZCLIP_FIELD_TLV(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupUdpPort, 3),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterGroupsServerCommandAddGroupIfIdentifyingResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterGroupsServerCommandAddGroupIfIdentifyingResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterGroupsServerCommandAddGroupIfIdentifyingResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterGroupsServerCommandAddGroupIfIdentifyingResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterGroupsServerCommandAddGroupIfIdentifyingResponseSpec);
}

// -----------------------------------------------------------------------------
// Scenes cluster (0x0005).

// Scenes cluster client (0x0005).
const EmberZclClusterSpec_t emberZclClusterScenesClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_SCENES,
};

// Scenes cluster server (0x0005).
const EmberZclClusterSpec_t emberZclClusterScenesServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_SCENES,
};

// Scenes cluster server (0x0005) - AddScene (0x00) command.
static const ZclipStructSpec emZclClusterScenesServerCommandAddSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandAddSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, sceneName),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, extensionFieldSets),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandAddSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandAddSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandAddSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandAddSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandAddSceneResponseSpec);
}

// Scenes cluster server (0x0005) - ViewScene (0x01) command.
static const ZclipStructSpec emZclClusterScenesServerCommandViewSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandViewSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandViewSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandViewSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 6, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, sceneName),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, extensionFieldSets),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandViewSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandViewSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandViewSceneResponseSpec);
}

// Scenes cluster server (0x0005) - RemoveScene (0x02) command.
static const ZclipStructSpec emZclClusterScenesServerCommandRemoveSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRemoveSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandRemoveSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRemoveSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandRemoveSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandRemoveSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandRemoveSceneResponseSpec);
}

// Scenes cluster server (0x0005) - RemoveAllScenes (0x03) command.
static const ZclipStructSpec emZclClusterScenesServerCommandRemoveAllScenesRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRemoveAllScenesRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandRemoveAllScenesResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRemoveAllScenesResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandRemoveAllScenesResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandRemoveAllScenesResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandRemoveAllScenesResponseSpec);
}

// Scenes cluster server (0x0005) - StoreScene (0x04) command.
static const ZclipStructSpec emZclClusterScenesServerCommandStoreSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandStoreSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandStoreSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandStoreSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandStoreSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandStoreSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandStoreSceneResponseSpec);
}

// Scenes cluster server (0x0005) - RecallScene (0x05) command.
static const ZclipStructSpec emZclClusterScenesServerCommandRecallSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRecallSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandRecallSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandRecallSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandRecallSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandRecallSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandRecallSceneResponseSpec);
}

// Scenes cluster server (0x0005) - GetSceneMembership (0x06) command.
static const ZclipStructSpec emZclClusterScenesServerCommandGetSceneMembershipRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandGetSceneMembershipRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandGetSceneMembershipResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandGetSceneMembershipResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 4, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, capacity),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD_ARRAY(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneList),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandGetSceneMembershipResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandGetSceneMembershipResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandGetSceneMembershipResponseSpec);
}

// Scenes cluster server (0x0005) - EnhancedAddScene (0x40) command.
static const ZclipStructSpec emZclClusterScenesServerCommandEnhancedAddSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandEnhancedAddSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, sceneName),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, extensionFieldSets),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandEnhancedAddSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandEnhancedAddSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandEnhancedAddSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandEnhancedAddSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandEnhancedAddSceneResponseSpec);
}

// Scenes cluster server (0x0005) - EnhancedViewScene (0x41) command.
static const ZclipStructSpec emZclClusterScenesServerCommandEnhancedViewSceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandEnhancedViewSceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandEnhancedViewSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandEnhancedViewSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 6, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, sceneName),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, extensionFieldSets),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandEnhancedViewSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandEnhancedViewSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandEnhancedViewSceneResponseSpec);
}

// Scenes cluster server (0x0005) - CopyScene (0x42) command.
static const ZclipStructSpec emZclClusterScenesServerCommandCopySceneRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandCopySceneRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, mode),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupIdFrom),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneIdFrom),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupIdTo),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneIdTo),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterScenesServerCommandCopySceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterScenesServerCommandCopySceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, groupIdFrom),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, sceneIdFrom),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterScenesServerCommandCopySceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterScenesServerCommandCopySceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterScenesServerCommandCopySceneResponseSpec);
}

// -----------------------------------------------------------------------------
// On/off cluster (0x0006).

// On/off cluster client (0x0006).
const EmberZclClusterSpec_t emberZclClusterOnOffClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_ON_OFF,
};

// On/off cluster server (0x0006).
const EmberZclClusterSpec_t emberZclClusterOnOffServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_ON_OFF,
};

// On/off cluster server (0x0006) - Off (0x00) command.
#define emZclClusterOnOffServerCommandOffRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOffResponseSpec);
}

// On/off cluster server (0x0006) - On (0x01) command.
#define emZclClusterOnOffServerCommandOnRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOnResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnResponseSpec);
}

// On/off cluster server (0x0006) - Toggle (0x02) command.
#define emZclClusterOnOffServerCommandToggleRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandToggleResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandToggleResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandToggleResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandToggleResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandToggleResponseSpec);
}

// On/off cluster server (0x0006) - OffWithEffect (0x40) command.
static const ZclipStructSpec emZclClusterOnOffServerCommandOffWithEffectRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffWithEffectRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectVariant),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOnOffServerCommandOffWithEffectResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffWithEffectResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOffWithEffectResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOffWithEffectResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOffWithEffectResponseSpec);
}

// On/off cluster server (0x0006) - OnWithRecallGlobalScene (0x41) command.
#define emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnWithRecallGlobalSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseSpec);
}

// On/off cluster server (0x0006) - OnWithTimedOff (0x42) command.
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithTimedOffRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, onOffControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, onTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, offWaitTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithTimedOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithTimedOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnWithTimedOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnWithTimedOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnWithTimedOffResponseSpec);
}

// -----------------------------------------------------------------------------
// Level Control cluster (0x0008).

// Level Control cluster client (0x0008).
const EmberZclClusterSpec_t emberZclClusterLevelControlClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_LEVEL_CONTROL,
};

// Level Control cluster server (0x0008).
const EmberZclClusterSpec_t emberZclClusterLevelControlServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_LEVEL_CONTROL,
};

// Level Control cluster server (0x0008) - MoveToLevel (0x00) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveToLevelRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveToLevelRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, level),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveToLevelResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveToLevelResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandMoveToLevelResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandMoveToLevelResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandMoveToLevelResponseSpec);
}

// Level Control cluster server (0x0008) - Move (0x01) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, moveMode),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, rate),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandMoveResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandMoveResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandMoveResponseSpec);
}

// Level Control cluster server (0x0008) - Step (0x02) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandStepRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStepRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, stepMode),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, stepSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandStepResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStepResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandStepResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandStepResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandStepResponseSpec);
}

// Level Control cluster server (0x0008) - Stop (0x03) command.
#define emZclClusterLevelControlServerCommandStopRequestSpec NULL
static const ZclipStructSpec emZclClusterLevelControlServerCommandStopResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStopResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandStopResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandStopResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandStopResponseSpec);
}

// Level Control cluster server (0x0008) - MoveToLevelWithOnOff (0x04) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveToLevelWithOnOffRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveToLevelWithOnOffRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, level),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveToLevelWithOnOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveToLevelWithOnOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandMoveToLevelWithOnOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandMoveToLevelWithOnOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandMoveToLevelWithOnOffResponseSpec);
}

// Level Control cluster server (0x0008) - MoveWithOnOff (0x05) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveWithOnOffRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveWithOnOffRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, moveMode),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, rate),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandMoveWithOnOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandMoveWithOnOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandMoveWithOnOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandMoveWithOnOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandMoveWithOnOffResponseSpec);
}

// Level Control cluster server (0x0008) - StepWithOnOff (0x06) command.
static const ZclipStructSpec emZclClusterLevelControlServerCommandStepWithOnOffRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStepWithOnOffRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, stepMode),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, stepSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, transitionTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterLevelControlServerCommandStepWithOnOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStepWithOnOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandStepWithOnOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandStepWithOnOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandStepWithOnOffResponseSpec);
}

// Level Control cluster server (0x0008) - StopWithOnOff (0x07) command.
#define emZclClusterLevelControlServerCommandStopWithOnOffRequestSpec NULL
static const ZclipStructSpec emZclClusterLevelControlServerCommandStopWithOnOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterLevelControlServerCommandStopWithOnOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterLevelControlServerCommandStopWithOnOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterLevelControlServerCommandStopWithOnOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterLevelControlServerCommandStopWithOnOffResponseSpec);
}

// -----------------------------------------------------------------------------
// Over the Air Bootloading cluster (0x2000).

// Over the Air Bootloading cluster client (0x2000).
const EmberZclClusterSpec_t emberZclClusterOtaBootloadClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_OTA_BOOTLOAD,
};

// Over the Air Bootloading cluster client (0x2000) - ImageNotify (0x00) command.
static const ZclipStructSpec emZclClusterOtaBootloadClientCommandImageNotifyRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadClientCommandImageNotifyRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, payloadType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, queryJitter),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, newFileVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadClientCommandImageNotifyResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadClientCommandImageNotifyResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadClientCommandImageNotifyResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOtaBootloadClientCommandImageNotifyResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOtaBootloadClientCommandImageNotifyResponseSpec);
}

// Over the Air Bootloading cluster server (0x2000).
const EmberZclClusterSpec_t emberZclClusterOtaBootloadServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_OTA_BOOTLOAD,
};

// Over the Air Bootloading cluster server (0x2000) - QueryNextImageRequest (0x01) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQueryNextImageRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQueryNextImageRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentFileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, hardwareVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQueryNextImageResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQueryNextImageResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 4, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, fileUri),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandQueryNextImageRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandQueryNextImageRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandQueryNextImageResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_QUERY_NEXT_IMAGE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandQueryNextImageRequestSpec,
                                 emZclClusterOtaBootloadServerCommandQueryNextImageResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x2000) - ImageBlockRequest (0x03) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImageBlockRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImageBlockRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 7, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, maxDataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImageBlockResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImageBlockResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 7, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, dataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageData),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandImageBlockRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandImageBlockRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandImageBlockResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_IMAGE_BLOCK_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandImageBlockRequestSpec,
                                 emZclClusterOtaBootloadServerCommandImageBlockResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x2000) - ImagePageRequest (0x04) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImagePageRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImagePageRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 9, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, maxDataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, pageSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, responseSpacing),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImagePageResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImagePageResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandImagePageRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandImagePageRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandImagePageResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_IMAGE_PAGE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandImagePageRequestSpec,
                                 emZclClusterOtaBootloadServerCommandImagePageResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x2000) - UpgradeEndRequest (0x06) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandUpgradeEndRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandUpgradeEndRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 4, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandUpgradeEndResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandUpgradeEndResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, upgradeTime),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandUpgradeEndRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandUpgradeEndRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandUpgradeEndResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_UPGRADE_END_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandUpgradeEndRequestSpec,
                                 emZclClusterOtaBootloadServerCommandUpgradeEndResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x2000) - QuerySpecificFileRequest (0x08) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQuerySpecificFileRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQuerySpecificFileRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentZigbeeStackVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQuerySpecificFileResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQuerySpecificFileResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 4, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING, fileUri),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandQuerySpecificFileRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandQuerySpecificFileRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandQuerySpecificFileResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_QUERY_SPECIFIC_FILE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandQuerySpecificFileRequestSpec,
                                 emZclClusterOtaBootloadServerCommandQuerySpecificFileResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// -----------------------------------------------------------------------------
// Endpoints.

// Endpoint specs.
static const EmberZclClusterSpec_t *emZclEndpointPrimarySpec[] = {
  &emberZclClusterOtaBootloadClientSpec,
  &emberZclClusterBasicServerSpec,
  &emberZclClusterIdentifyServerSpec,
  &emberZclClusterGroupsServerSpec,
  &emberZclClusterScenesServerSpec,
  &emberZclClusterOnOffServerSpec,
  &emberZclClusterLevelControlServerSpec,
  NULL,
};

// Endpoint entries.
const EmZclEndpointEntry_t emZclEndpointTable[] = {
  {1, 0x0101, emZclEndpointPrimarySpec},
};
const size_t emZclEndpointCount = COUNTOF(emZclEndpointTable);

// -----------------------------------------------------------------------------
// Attributes.

// Attribute default, minimum, and maximum data.
const uint8_t emZclAttributeDefaultMinMaxData[] = {
#if BIGENDIAN_CPU
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF,
  0x00, 0x01,
  0x03,
#else
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF,
  0x01, 0x00,
  0x03,
#endif
};

// Attribute default, minimum, and maximum lookup table.
const size_t emZclAttributeDefaultMinMaxLookupTable[] = {
  0, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_UPGRADE_SERVER_ID: +DEFAULT, -MINIMUM, -MAXIMUM,
  8, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_FILE_OFFSET: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT: +DEFAULT, -MINIMUM, -MAXIMUM,
  14, // EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_VERSION: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_GROUPS_SERVER_ATTRIBUTE_GROUPS_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_SCENES_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  12, // EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_ATTRIBUTE_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
};

// Attribute entries.
const EmZclAttributeEntry_t emZclAttributeTable[] = {
  {&emberZclClusterBasicClientSpec, EMBER_ZCL_CLUSTER_BASIC_CLIENT_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicClientSpec, EMBER_ZCL_CLUSTER_BASIC_CLIENT_ATTRIBUTE_BASIC_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyClientSpec, EMBER_ZCL_CLUSTER_IDENTIFY_CLIENT_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyClientSpec, EMBER_ZCL_CLUSTER_IDENTIFY_CLIENT_ATTRIBUTE_IDENTIFY_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterGroupsClientSpec, EMBER_ZCL_CLUSTER_GROUPS_CLIENT_ATTRIBUTE_GROUPS_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterGroupsClientSpec, EMBER_ZCL_CLUSTER_GROUPS_CLIENT_ATTRIBUTE_GROUPS_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesClientSpec, EMBER_ZCL_CLUSTER_SCENES_CLIENT_ATTRIBUTE_SCENES_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesClientSpec, EMBER_ZCL_CLUSTER_SCENES_CLIENT_ATTRIBUTE_SCENES_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffClientSpec, EMBER_ZCL_CLUSTER_ON_OFF_CLIENT_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffClientSpec, EMBER_ZCL_CLUSTER_ON_OFF_CLIENT_ATTRIBUTE_ON_OFF_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterLevelControlClientSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_CLIENT_ATTRIBUTE_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterLevelControlClientSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_CLIENT_ATTRIBUTE_LEVEL_CONTROL_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_UPGRADE_SERVER_ID, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT, 0, 0, 8, EMBER_ZCLIP_TYPE_BINARY},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_FILE_OFFSET, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 8, 1, 4, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_IMAGE_UPGRADE_STATUS, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 12, 2, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 13, 2, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_VERSION, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 15, 3, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_MANUFACTURER_NAME, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 16, 4, 33, EMBER_ZCLIP_TYPE_UINT8_LENGTH_STRING},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_POWER_SOURCE, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 49, 4, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 50, 4, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_TIME, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_WRITABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 52, 5, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 54, 5, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_ATTRIBUTE_GROUP_NAME_SUPPORT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 56, 6, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_ATTRIBUTE_GROUPS_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 57, 6, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_SCENE_COUNT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 59, 7, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_CURRENT_SCENE, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 60, 7, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_CURRENT_GROUP, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 61, 7, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_SCENE_VALID, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 63, 7, 1, EMBER_ZCLIP_TYPE_BOOLEAN},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_SCENE_NAME_SUPPORT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 64, 7, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_ATTRIBUTE_SCENES_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 65, 7, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_REPORTABLE, 67, 8, 1, EMBER_ZCLIP_TYPE_BOOLEAN},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 68, 8, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_ATTRIBUTE_CURRENT_LEVEL, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_REPORTABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 70, 9, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_ATTRIBUTE_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 71, 9, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadServerSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 73, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadServerSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_REPORTING_STATUS_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 73, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
};

// -----------------------------------------------------------------------------
// Commands.

// Command entries.
const EmZclCommandEntry_t emZclCommandTable[] = {
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_COMMAND_IMAGE_NOTIFY, emZclClusterOtaBootloadClientCommandImageNotifyRequestSpec, (EmZclRequestHandler)emberZclClusterOtaBootloadClientCommandImageNotifyRequestHandler},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_COMMAND_RESET_TO_FACTORY_DEFAULTS, emZclClusterBasicServerCommandResetToFactoryDefaultsRequestSpec, (EmZclRequestHandler)emberZclClusterBasicServerCommandResetToFactoryDefaultsRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY, emZclClusterIdentifyServerCommandIdentifyRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandIdentifyRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY_QUERY, emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandIdentifyQueryRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_E_Z_MODE_INVOKE, emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandEZModeInvokeRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_UPDATE_COMMISSION_STATE, emZclClusterIdentifyServerCommandUpdateCommissionStateRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandUpdateCommissionStateRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_TRIGGER_EFFECT, emZclClusterIdentifyServerCommandTriggerEffectRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandTriggerEffectRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_ADD_GROUP, emZclClusterGroupsServerCommandAddGroupRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandAddGroupRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_VIEW_GROUP, emZclClusterGroupsServerCommandViewGroupRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandViewGroupRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_GET_GROUP_MEMBERSHIP, emZclClusterGroupsServerCommandGetGroupMembershipRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandGetGroupMembershipRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_REMOVE_GROUP, emZclClusterGroupsServerCommandRemoveGroupRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandRemoveGroupRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_REMOVE_ALL_GROUPS, emZclClusterGroupsServerCommandRemoveAllGroupsRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandRemoveAllGroupsRequestHandler},
  {&emberZclClusterGroupsServerSpec, EMBER_ZCL_CLUSTER_GROUPS_SERVER_COMMAND_ADD_GROUP_IF_IDENTIFYING, emZclClusterGroupsServerCommandAddGroupIfIdentifyingRequestSpec, (EmZclRequestHandler)emberZclClusterGroupsServerCommandAddGroupIfIdentifyingRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_ADD_SCENE, emZclClusterScenesServerCommandAddSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandAddSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_VIEW_SCENE, emZclClusterScenesServerCommandViewSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandViewSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_REMOVE_SCENE, emZclClusterScenesServerCommandRemoveSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandRemoveSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_REMOVE_ALL_SCENES, emZclClusterScenesServerCommandRemoveAllScenesRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandRemoveAllScenesRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_STORE_SCENE, emZclClusterScenesServerCommandStoreSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandStoreSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_RECALL_SCENE, emZclClusterScenesServerCommandRecallSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandRecallSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_GET_SCENE_MEMBERSHIP, emZclClusterScenesServerCommandGetSceneMembershipRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandGetSceneMembershipRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_ENHANCED_ADD_SCENE, emZclClusterScenesServerCommandEnhancedAddSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandEnhancedAddSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_ENHANCED_VIEW_SCENE, emZclClusterScenesServerCommandEnhancedViewSceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandEnhancedViewSceneRequestHandler},
  {&emberZclClusterScenesServerSpec, EMBER_ZCL_CLUSTER_SCENES_SERVER_COMMAND_COPY_SCENE, emZclClusterScenesServerCommandCopySceneRequestSpec, (EmZclRequestHandler)emberZclClusterScenesServerCommandCopySceneRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF, emZclClusterOnOffServerCommandOffRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOffRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON, emZclClusterOnOffServerCommandOnRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_TOGGLE, emZclClusterOnOffServerCommandToggleRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandToggleRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF_WITH_EFFECT, emZclClusterOnOffServerCommandOffWithEffectRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOffWithEffectRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_RECALL_GLOBAL_SCENE, emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_TIMED_OFF, emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnWithTimedOffRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_MOVE_TO_LEVEL, emZclClusterLevelControlServerCommandMoveToLevelRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandMoveToLevelRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_MOVE, emZclClusterLevelControlServerCommandMoveRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandMoveRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_STEP, emZclClusterLevelControlServerCommandStepRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandStepRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_STOP, emZclClusterLevelControlServerCommandStopRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandStopRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_MOVE_TO_LEVEL_WITH_ON_OFF, emZclClusterLevelControlServerCommandMoveToLevelWithOnOffRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandMoveToLevelWithOnOffRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_MOVE_WITH_ON_OFF, emZclClusterLevelControlServerCommandMoveWithOnOffRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandMoveWithOnOffRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_STEP_WITH_ON_OFF, emZclClusterLevelControlServerCommandStepWithOnOffRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandStepWithOnOffRequestHandler},
  {&emberZclClusterLevelControlServerSpec, EMBER_ZCL_CLUSTER_LEVEL_CONTROL_SERVER_COMMAND_STOP_WITH_ON_OFF, emZclClusterLevelControlServerCommandStopWithOnOffRequestSpec, (EmZclRequestHandler)emberZclClusterLevelControlServerCommandStopWithOnOffRequestHandler},
};
const size_t emZclCommandCount = COUNTOF(emZclCommandTable);
