// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_ZCL_CORE
#include EMBER_AF_API_ZCL_SCENES_SERVER
#include EMBER_AF_API_STACK

// EraseScene function declarations.
void emZclLevelControlServerEraseSceneHandler(uint8_t tableIdx);
void emZclOnOffServerEraseSceneHandler(uint8_t tableIdx);
void emberZclEraseSceneCallback(uint8_t tableIdx);

void emZclEraseScene(uint8_t tableIdx)
{
  emZclLevelControlServerEraseSceneHandler(tableIdx);
  emZclOnOffServerEraseSceneHandler(tableIdx);
  emberZclEraseSceneCallback(tableIdx);
}

// AddScene function declarations.
bool emZclLevelControlServerAddSceneHandler(EmberZclClusterId_t clusterId, uint8_t tableIdx, const uint8_t *sceneData, uint8_t length);
bool emZclOnOffServerAddSceneHandler(EmberZclClusterId_t clusterId, uint8_t tableIdx, const uint8_t *sceneData, uint8_t length);
bool emberZclAddSceneCallback(EmberZclClusterId_t clusterId, uint8_t tableIdx, const uint8_t *sceneData, uint8_t length);

bool emZclAddScene(EmberZclClusterId_t clusterId, uint8_t tableIdx, const uint8_t *sceneData, uint8_t length)
{
  return (emZclLevelControlServerAddSceneHandler(clusterId, tableIdx, sceneData, length)
          || emZclOnOffServerAddSceneHandler(clusterId, tableIdx, sceneData, length)
          || emberZclAddSceneCallback(clusterId, tableIdx, sceneData, length));
}

// RecallScene function declarations.
void emZclLevelControlServerRecallSceneHandler(EmberZclEndpointId_t endpointId, uint8_t tableIdx, uint32_t transitionTime100mS);
void emZclOnOffServerRecallSceneHandler(EmberZclEndpointId_t endpointId, uint8_t tableIdx, uint32_t transitionTime100mS);
void emberZclRecallSceneCallback(EmberZclEndpointId_t endpointId, uint8_t tableIdx, uint32_t transitionTime100mS);

void emZclRecallScene(EmberZclEndpointId_t endpointId, uint8_t tableIdx, uint32_t transitionTime100mS)
{
  emZclLevelControlServerRecallSceneHandler(endpointId, tableIdx, transitionTime100mS);
  emZclOnOffServerRecallSceneHandler(endpointId, tableIdx, transitionTime100mS);
  emberZclRecallSceneCallback(endpointId, tableIdx, transitionTime100mS);
}

// StoreScene function declarations.
void emZclLevelControlServerStoreSceneHandler(EmberZclEndpointId_t endpointId, uint8_t tableIdx);
void emZclOnOffServerStoreSceneHandler(EmberZclEndpointId_t endpointId, uint8_t tableIdx);
void emberZclStoreSceneCallback(EmberZclEndpointId_t endpointId, uint8_t tableIdx);

void emZclStoreScene(EmberZclEndpointId_t endpointId, uint8_t tableIdx)
{
  emZclLevelControlServerStoreSceneHandler(endpointId, tableIdx);
  emZclOnOffServerStoreSceneHandler(endpointId, tableIdx);
  emberZclStoreSceneCallback(endpointId, tableIdx);
}

// CopyScene function declarations.
void emZclLevelControlServerCopySceneHandler(uint8_t srcTableIdx, uint8_t dstTableIdx);
void emZclOnOffServerCopySceneHandler(uint8_t srcTableIdx, uint8_t dstTableIdx);
void emberZclCopySceneCallback(uint8_t srcTableIdx, uint8_t dstTableIdx);

void emZclCopyScene(uint8_t srcTableIdx, uint8_t dstTableIdx)
{
  emZclLevelControlServerCopySceneHandler(srcTableIdx, dstTableIdx);
  emZclOnOffServerCopySceneHandler(srcTableIdx, dstTableIdx);
  emberZclCopySceneCallback(srcTableIdx, dstTableIdx);
}

// ViewScene function declarations.
void emZclLevelControlServerViewSceneHandler(uint8_t tableIdx, uint8_t **ppExtFldData);
void emZclOnOffServerViewSceneHandler(uint8_t tableIdx, uint8_t **ppExtFldData);
void emberZclViewSceneCallback(uint8_t tableIdx, uint8_t **ppExtFldData);

void emZclViewScene(uint8_t tableIdx, uint8_t **ppExtFldData)
{
  emZclLevelControlServerViewSceneHandler(tableIdx, ppExtFldData);
  emZclOnOffServerViewSceneHandler(tableIdx, ppExtFldData);
  emberZclViewSceneCallback(tableIdx, ppExtFldData);
}

// PrintInfoScene function declarations.
void emZclLevelControlServerPrintInfoSceneHandler(uint8_t tableIdx);
void emZclOnOffServerPrintInfoSceneHandler(uint8_t tableIdx);
void emberZclPrintInfoSceneCallback(uint8_t tableIdx);

void emZclPrintInfoScene(uint8_t tableIdx)
{
  emZclLevelControlServerPrintInfoSceneHandler(tableIdx);
  emZclOnOffServerPrintInfoSceneHandler(tableIdx);
  emberZclPrintInfoSceneCallback(tableIdx);
}

// PreAttributeChange function declarations.
bool emZclGroupsServerPreAttributeChangeHandler(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);
bool emberZclPreAttributeChangeCallback(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

bool emZclPreAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength)
{
  return (emZclGroupsServerPreAttributeChangeHandler(endpointId, clusterSpec, attributeId, buffer, bufferLength)
          && emberZclPreAttributeChangeCallback(endpointId, clusterSpec, attributeId, buffer, bufferLength));
}

// PostAttributeChange function declarations.
void emZclIdentifyServerPostAttributeChangeHandler(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);
void emZclReportingPostAttributeChangeHandler(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);
void emberZclPostAttributeChangeCallback(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclPostAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength)
{
  emZclIdentifyServerPostAttributeChangeHandler(endpointId, clusterSpec, attributeId, buffer, bufferLength);
  emZclReportingPostAttributeChangeHandler(endpointId, clusterSpec, attributeId, buffer, bufferLength);
  emberZclPostAttributeChangeCallback(endpointId, clusterSpec, attributeId, buffer, bufferLength);
}

// Notification function declarations.
void emberZclNotificationCallback(const EmberZclNotificationContext_t *context, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclNotification(const EmberZclNotificationContext_t *context, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength)
{
  emberZclNotificationCallback(context, clusterSpec, attributeId, buffer, bufferLength);
}

// OkToSleep function declarations.
bool emberAfPluginIdleSleepOkToSleepCallback(uint32_t durationMs);

bool emberAfOkToSleep(uint32_t durationMs)
{
  return emberAfPluginIdleSleepOkToSleepCallback(durationMs);
}

// WakeUp function declarations.
void emberAfPluginIdleSleepWakeUpCallback(uint32_t durationMs);

void emberAfPluginIdleSleepWakeUp(uint32_t durationMs)
{
  emberAfPluginIdleSleepWakeUpCallback(durationMs);
}

// OkToIdle function declarations.
bool emberAfPluginIdleSleepOkToIdleCallback(uint32_t durationMs);

bool emberAfOkToIdle(uint32_t durationMs)
{
  return emberAfPluginIdleSleepOkToIdleCallback(durationMs);
}

// Active function declarations.
void emberAfPluginIdleSleepActiveCallback(uint32_t durationMs);

void emberAfPluginIdleSleepActive(uint32_t durationMs)
{
  emberAfPluginIdleSleepActiveCallback(durationMs);
}

// Main function declarations.
void emberAfMainCallback(MAIN_FUNCTION_PARAMETERS);

void emAfMain(MAIN_FUNCTION_PARAMETERS)
{
  emberAfMainCallback(MAIN_FUNCTION_ARGUMENTS);
}

// Init function declarations.
void emZclInitHandler(void);
void emZclOtaBootloadClientInitCallback(void);
void emZclOtaBootloadStorageEepromInitCallback(void);
void emZclScenesServerInitHandler(void);
void emberAfInitCallback(void);
void emberAfPluginEepromInitCallback(void);
void emberCommandReaderInit(void);

void emAfInit(void)
{
  emZclInitHandler();
  emZclOtaBootloadClientInitCallback();
  emZclOtaBootloadStorageEepromInitCallback();
  emZclScenesServerInitHandler();
  emberAfInitCallback();
  emberAfPluginEepromInitCallback();
  emberCommandReaderInit();
}

// Tick function declarations.
void emberAfPluginCliTickCallback(void);
void emberAfPluginHeartbeatTickCallback(void);
void emberAfPluginIdleSleepTickCallback(void);
void emberAfTickCallback(void);
void emberSerialBufferTick(void);
void emberTick(void);

void emAfTick(void)
{
  emberAfPluginCliTickCallback();
  emberAfPluginHeartbeatTickCallback();
  emberAfPluginIdleSleepTickCallback();
  emberAfTickCallback();
  emberSerialBufferTick();
  emberTick();
}

// MarkApplicationBuffers function declarations.
void emZclAccessMarkApplicationBuffersHandler(void);
void emZclCacheMarkApplicationBuffersHandler(void);
void emZclDtlsManagerMarkBuffers(void);
void emZclReportingMarkApplicationBuffersHandler(void);
void emZclResourceDirectoryClientMarkBuffers(void);
void emberAfMarkApplicationBuffersCallback(void);

void emAfMarkApplicationBuffers(void)
{
  emZclAccessMarkApplicationBuffersHandler();
  emZclCacheMarkApplicationBuffersHandler();
  emZclDtlsManagerMarkBuffers();
  emZclReportingMarkApplicationBuffersHandler();
  emZclResourceDirectoryClientMarkBuffers();
  emberAfMarkApplicationBuffersCallback();
}

// NetworkStatus function declarations.
void emZclBindingNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);
void emZclCacheNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);
void emZclGroupNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);
void emZclOtaBootloadClientNetworkStatusCallback(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);
void emZclReportingNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);
void emberAfNetworkStatusCallback(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);

void emberNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason)
{
  emZclBindingNetworkStatusHandler(newNetworkStatus, oldNetworkStatus, reason);
  emZclCacheNetworkStatusHandler(newNetworkStatus, oldNetworkStatus, reason);
  emZclGroupNetworkStatusHandler(newNetworkStatus, oldNetworkStatus, reason);
  emZclOtaBootloadClientNetworkStatusCallback(newNetworkStatus, oldNetworkStatus, reason);
  emZclReportingNetworkStatusHandler(newNetworkStatus, oldNetworkStatus, reason);
  emberAfNetworkStatusCallback(newNetworkStatus, oldNetworkStatus, reason);
}
