// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the Scenes Server plugin.
#include "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/scenes-server/scenes-server-tokens.h"

// Token header for the Level Control Server plugin.
#include "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/level-control-server/level-control-server-tokens.h"

// Token header for the On/Off Server plugin.
#include "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/on-off-server/on-off-server-tokens.h"

// Token header for the ZCL Core plugin.
#include "../../../sdks/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/zcl/zcl-core/zcl-core-token.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

